version: "3.7"

services:
  node_app:
    image: node:16-alpine3.11
    ports:
      - 3000:${PORT}
    build: app/.
    env_file:
      - .env
    networks: 
      - net

  redis:
    image: redis:latest
    ports:
      - 6379:${REDIS_PORT}
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks: 
      - net

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=${REDIS_USER}
      - HTTP_PASSWORD=${REDIS_PASS}
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks: 
      - net
volumes:
  redis-data:

networks:
  net: